Userstory1
ArianeDahl/capstone-project pull request #5
Opened 2023-03-07 15:12 UTC by ArianeDahl

Please check :)

2023-03-07 15:44 UTC, Kheirah requested changes
Good start!

Please format all your files with prettier. That'll make it easier to read.
Add functionality to your two buttons. It's not enough to have buttons; they really need to do something too.

2023-03-07 15:44 UTC, Kheirah commented on components/FruitButton.js
> +`;
Looks like you haven't used prettier. Please format every life before submitting your PR for a review. Formatted code really helps with readability.

2023-03-07 15:44 UTC, Kheirah commented on pages/index.js
> +import Header from "../components/Header";
Be consistent with your paths. Either stick with absolute paths or relative ones. Don't mix them.

2023-03-07 15:44 UTC, Kheirah commented on components/FruitButton.js
> +    </ButtonComponent>
The button isn't doing anything, yet. But it should be doing something. You should add an `onClick` event to render data for example. Simply having a button that doesn't do anything won't get you passed quality assurance. Better fix it now =)

2023-03-08 08:55 UTC, TuncAlt approved these changes

2023-03-08 08:55 UTC, TuncAlt commented
Looks Good!

2023-03-08 09:02 UTC, merged